name: Build and Push Docker Image

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  docker-build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: ðŸ›Žï¸ Checkout code
        uses: actions/checkout@v4

      - name: ðŸ” Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: ðŸ—ï¸ Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: ðŸ³ Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Docker/Dockerfile.prod
          push: true
          tags: |
            ghcr.io/mahmoudashours/elmwajib:latest
            ghcr.io/mahmoudashours/elmwajib:0.1
          cache-from: type=gha
          cache-to: type=gha,mode=max
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: docker-build
  #   steps:
  #     - name: Deploy over SSH
  #       uses: appleboy/ssh-action@v1.0.0
  #       with:
  #         host: ${{ secrets.SERVER_HOST }}
  #         username: ${{ secrets.SERVER_USER }}
  #         key: ${{ secrets.SERVER_SSH_KEY }}
  #         script: |
  #           cd /home/ubuntu/dawah_center

  #           # Write .env from GitHub Secrets
  #           cat > .env <<EOL
  #           APP_ENV=production
  #           APP_DEBUG=false
  #           APP_KEY=${{ secrets.APP_KEY }}
  #           DB_HOST=mysql
  #           DB_DATABASE=${{ secrets.DB_DATABASE }}
  #           DB_USERNAME=${{ secrets.DB_USERNAME }}
  #           DB_PASSWORD=${{ secrets.DB_PASSWORD }}
  #           MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
  #           REDIS_HOST=redis
  #           ELASTICSEARCH_HOST=elasticsearch
  #           EOL

  #           # Pull latest images & restart services
  #           docker-compose pull
  #           docker-compose up -d